<a href="https://colab.research.google.com/github/dasdasqs2/pdm05/blob/master/numpy/numpy_1_intro2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## python module 1. numpy
### 행렬연산 II

1.   행렬곱
2.   Boradcast
3.   전치행렬
4.   요소 접근
    - indexing
    - slicing



In [ ]:
import numpy as np # 라이브러리의 별명을 지정하는 방식을 사용



---



In [ ]:
# np.dot(A,B)

### numpy 행렬 곱 (dot product)

#### 행렬 곱 (dot product)

- **행렬 곱 (dot product)**


> A 행렬과 B 행렬의 행렬 곱 (dot product)는 **np.dot**(A,B)로 나타내며, 행렬 A의 열벡터와 B 행렬의 행벡터가 같아야 한다.


> 만약 같지 않으면 **reshape 또는 전치행렬(transpose) 등을 사용하여 형 변환을 한 후에 행렬 곱을 실행**해야 한다.





In [ ]:
A = np.array([ [1,2,3], [4,5,6] ]) # 2x3 행렬
B = np.array([ [-1,-2], [-3,-4], [-5,-6] ]) # 3x2 행렬

# (2x3) dot product (3x2) == (2x2) 행렬
C = np.dot(A, B) # 행렬 곱 수행

# matrix A, B 형상 출력 => shape
print("A.shape = ", A.shape, ", B.shape = ", B.shape)
print("C.shape = ", C.shape)
print(C)

('A.shape = ', (2, 3), ', B.shape = ', (3, 2))
('C.shape = ', (2, 2))
[[-22 -28]
 [-49 -64]]


** 주의

>    A     x    B   =  C  
> (2x**3) x (3**x2) = (2x2)

=> 이렇듯 **행렬 A의 열의 수와  B의 행의 수가 같아야** 한다!

#### 행렬 곱 (dot product) (ll)

행렬 곱은 사칙연산과는 다른 특징을 가진다.

- 행렬 곱은 행렬의 원소 개수가 같아야만 계산할 수 있는 사칙연산의 한계를 벗어나


> 1.   행렬 곱 조건을 만족하는 다양한 크기의 행렬을 연속으로 만들고
2.   행렬 곱을 연속으로 계산하면서
3. 결괏값을 만들 수 있기 때문에 머신러닝과 이미지 프로세싱 분야에서 자주 사용된다.

        예) 입력 행렬 형상이 64X64이고, 결과 행렬 형상이 64X10이라면, 중간에 dot product 를 만족시키는 어떤 형상의 행렬이라도 가질 수 있다.
        
> 행렬 곱을 사용하지 않고 산술 연산만 가능하다면, 입력 행렬의 64X64 크기를 가지는 특성 값만을 사용해야 하기 때문에 다양한 특성을 갖는 필터 개발이 불가능하다.

### numpy broadcast (**브로드캐스트**)

- 행렬의 사칙연산은 기본적으로 두 개의 행렬 크기가 같은 경우에만 수행할 수 있다.
- 그러나 numpy에서는 **크기가 다른 두 행렬간에도 사칙연산(+,-,x,/)를 사용할 수 있는데 이를 브로드캐스트(broadcast)**라고 지칭한다.
- 브로드캐스트는 차원이 작은 쪽이 큰 쪽의 행 단위로 반복적으로 크기를 맞춘 후에 계산된다.

In [1]:
import numpy as np

In [2]:
A = np.array([ [1,2], [3,4] ])
A

array([[1, 2],
       [3, 4]])

In [3]:
A = np.array([ [1,2], [3,4] ])
b = 5

print(A+b)

[[6 7]
 [8 9]]


=> b가 2x2 행렬로 바뀐다.


>      b = 5   =>   (5 5)
                  (5 5)

In [ ]:
C = np.array([ [1,2], [3,4] ])
D = np.array([4,5])

print(C+D)

=> D가 2x2 행렬로 바뀐다.


>      D = (4 5)  =>  (4 5)
                    (4 5)



- **브로드캐스트는 사칙연산에만 사용된다**는 것을 반드시 기억할 것! **행렬 곱에는 적용안됨!!!**

### numpy 전치행렬 (transpose)

- 어떤 행렬의 전치행렬은 원본 행렬의 **열은 행으로, 행은 열로** 바꾼 것이다.
- 원본 행렬을 A라고 하면 전치행렬은 **A.T** 로 나타낸다.
- 즉, 1행은 1열로 바꾸고 2행은 2열로, 3행은 3열로 바꾼 행렬을 의미한다.



In [6]:
A = np.array([ [1,2],[3,4],[5,6] ]) # 3x2행렬
B = A.T  # A의 전치행렬, 2x3행렬

print("A.shape ==", A.shape, ", B.shape ==", B.shape)
print(A)
print(B)

('A.shape ==', (3, 2), ', B.shape ==', (2, 3))
[[1 2]
 [3 4]
 [5 6]]
[[1 3 5]
 [2 4 6]]


In [7]:
np.dot(A,B)

array([[ 5, 11, 17],
       [11, 25, 39],
       [17, 39, 61]])

In [12]:
# vector 전치행렬

C = np.array([1,2,3,4,5]) # vector, matrix 아님
C,C.ndim

(array([1, 2, 3, 4, 5]), 1)

In [10]:
C.shape

(5,)

In [15]:
# 변화가 없다 (numpy 기본벡터의 전치행렬은)
D = C.T  # C는 벡터이므로 transpose 안됨
D

array([1, 2, 3, 4, 5])

In [16]:
E = C.reshape(1,5) # 1x5 matrix
F = E.T  # E의 전치행렬

print("C.shape ==", C.shape, ", D.shape ==", D.shape)
print("E.shape ==", E.shape, ", F.shape ==", F.shape)
print(E)
print(F)

('C.shape ==', (5,), ', D.shape ==', (5,))
('E.shape ==', (1, 5), ', F.shape ==', (5, 1))
[[1 2 3 4 5]]
[[1]
 [2]
 [3]
 [4]
 [5]]


### numpy 행렬 원소 접근
- indexing
- slicing

####  indexing & slicing

- **행렬 원소 접근(l)**


> 행렬 원소를 명시적(explicit)으로 접근하기 위해서는 리스트에서처럼, 인덱싱 & 슬라이싱 모두 사용이 가능하다.

          예1) A[0,0] 또는 A[0][0]은 1행 1열, A[2,1] 또는 A[2][1]은 3행 2열임
          예2) A[ : , 0] 은 모든 행 1열을 나타냄
          예3) A[0:-1, 1:2] 인덱스 0인 1행부터 인덱스 -1-1=-2인 2행까지의 모든 데이터,
                            그리고 인덱스 1인 2열부터 인덱스 2-1=1인 2열까지의 모든 데이터
          예4) A[ :, : ] 은 모든 행, 모든 열



In [21]:
A = np.array([10,20,30,40,50,60])
A

array([10, 20, 30, 40, 50, 60])

In [22]:
# 예제1

A = np.array([10,20,30,40,50,60]).reshape(3,2)

print("A.shape = ", A.shape)
print(A)
A

('A.shape = ', (3, 2))
[[10 20]
 [30 40]
 [50 60]]


array([[10, 20],
       [30, 40],
       [50, 60]])

In [23]:
# 예제2 - 인덱싱

print("A[0,0] ==", A[0,0], ", A[0][0] ==", A[0][0])
print("A[2,1] ==", A[2,1], ", A[2][1] ==", A[2][1])

('A[0,0] ==', 10, ', A[0][0] ==', 10)
('A[2,1] ==', 60, ', A[2][1] ==', 60)


In [24]:
# 예제3 - 슬라이싱

print("A[0:-1, 1:2] ==", A[0:-1, 1:2])  # == A[0:2, 1:2]

('A[0:-1, 1:2] ==', array([[20],
       [40]]))


In [25]:
A[0:2, 1:2]

array([[20],
       [40]])

In [26]:
# 예제4 - 슬라이싱

print("A[ :, 0] ==", A[:, 0])
print("A[ :, :] ==", A[:, :])

('A[ :, 0] ==', array([10, 30, 50]))
('A[ :, :] ==', array([[10, 20],
       [30, 40],
       [50, 60]]))


## [도전] B = np.array([10,20,30,40,50,60]).reshpe(2,3)에 대하여 위의 인덱싱과슬라이싱을 해보세요

In [31]:
B = np.array([10,20,30,40,50,60]).reshape(2,3)
B

array([[10, 20, 30],
       [40, 50, 60]])

In [32]:
# 인덱싱
print("B[0,0] ==", B[0,0], ", B[0][0] ==", B[0][0])
print("B[1,2] ==", B[1,2], ", B[1][2] ==", B[1][2])

('B[0,0] ==', 10, ', B[0][0] ==', 10)
('B[1,2] ==', 60, ', B[1][2] ==', 60)


In [34]:
# 슬라이싱
print("B[0:-1, 1:2] ==", B[0:-1, 1:2])  # == B[0:2, 1:2]

('B[0:-1, 1:2] ==', array([[20]]))


#### iterator

- **행렬 원소 접근(ll)**


> 명시적(explicit) 인덱싱 & 슬라이싱 이외에 **행렬 모든 원소를 access하는 경우에는 iterator** 사용이 가능하다.


> numpy iterator는 C++, Java iterator처럼 next() 메서드를 통해,                     
                데이터값을 처음부터 끝까지 순차적으로 읽어들이는 방법을 제공한다.





In [ ]:
import numpy as np

A = np.array([ [10,20,30,40], [50,60,70,80] ])

print(A)
print("A.shape = ", A.shape)


In [ ]:
# 행렬 A의 iterator 생성

it = np.nditer(A, flags=['multi_index'], op_flags=['readwrite'])

while not it.finished:
  
  idx = it.multi_index
  
  print("current value => ", A[idx])
  
  it.iternext()

2x4 행렬인 경우,

> (0,0) => (0,1) => (0,2) => (0,3) => (1,0) => (1,1) => (1,2) => (1,3)   순서대로 access
 




---

