<a href="https://colab.research.google.com/github/dasdasqs2/pdm05/blob/master/numpy/numpy_2_array_ipynb.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# numpy array

- 생성
- 구조 살펴보기
- 수학연산 (columnwise, rowwise)

In [ ]:
from numpy import asarray
# define data as a list
data = [[1,2,3], [4,5,6]]
# convert to a numpy array
data = asarray(data)
# summarize the array content
print(data)
# summarize the array shape
print(data.shape)

[[1 2 3]
 [4 5 6]]
(2, 3)


## Print rows

In [ ]:
# enumerate rows in a numpy array
from numpy import asarray
# define data as a list
data = [[1,2,3], [4,5,6]]
# convert to a numpy array
data = asarray(data)
# step through rows
for row in range(data.shape[0]):
	print(data[row,:])

[1 2 3]
[4 5 6]


## Print columns

In [ ]:
data

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
# enumerate rows in a numpy array
from numpy import asarray
# define data as a list
data = [[1,2,3], [4,5,6]]
# convert to a numpy array
data = asarray(data)
print(data)
# step through columns
for col in range(data.shape[1]):
	print(data[:,col])

[[1 2 3]
 [4 5 6]]
[1 4]
[2 5]
[3 6]


## NumPy Array Operations By Row and Column
- axis=None: Apply operation array-wise.
- axis=0: Apply operation column-wise, across all rows for each column.
- axis=1: Apply operation row-wise, across all columns for each row.

In [ ]:
# sum values array-wise
from numpy import asarray
# define data as a list
data = [[1,2,3], [4,5,6]]
# convert to a numpy array
data = asarray(data)
# summarize the array content
print(data)
# sum data by array
result = data.sum(axis=None)
# summarize the result
print(result)

[[1 2 3]
 [4 5 6]]
21


### Axis=0 Column-Wise Operation (수직으로)



In [ ]:
# sum values column-wise
from numpy import asarray
# define data as a list
data = [[1,2,3], [4,5,6]]
# convert to a numpy array
data = asarray(data)
# summarize the array content
print(data)
# sum data by column
result = data.sum(axis=0)
# summarize the result
print(result)

[[1 2 3]
 [4 5 6]]
[5 7 9]


### Axis=1 Row-Wise Operation (수평으로)

In [ ]:
# sum values row-wise
from numpy import asarray
# define data as a list
data = [[1,2,3], [4,5,6]]
# convert to a numpy array
data = asarray(data)
# summarize the array content
print(data)
# sum data by row
result = data.sum(axis=1)
# summarize the result
print(result)

[[1 2 3]
 [4 5 6]]
[ 6 15]


## [Challenge]
- 3d-array
    * axis = 0
    * axis = 1
    * axis = 2
    * axis = (0,1)

## [도전하기]

- 3차원 배열을 리스트로부터 만드시오.

In [ ]:
# Make 3d-array in numpy
'''
data = [[1,2,3], [4,5,6]]
'''

### 잘못된 방법

In [ ]:
data3d = [[1,2,3], [4,5,6], [7,8,9]]

In [ ]:
from numpy import asarray
data3d = asarray(data3d)

In [ ]:
data3d.ndim

2

### 3차원배열 : n x m x l, (n,m,l)

In [ ]:
data3d = [[[1,2,3], [4,5,6]], [[1,2,3], [4,5,6]], [[1,2,3], [4,5,6]]]
data3d = asarray(data3d)

In [ ]:
data3d.ndim

3

In [ ]:
data3d.shape

(3, 2, 3)

In [ ]:
data3d

array([[[1, 2, 3],
        [4, 5, 6]],

       [[1, 2, 3],
        [4, 5, 6]],

       [[1, 2, 3],
        [4, 5, 6]]])

In [ ]:
data3d.sum(axis=0) # axis=0, Column-Wise 방법, 수직방향으로 합산한 1차원 array 결과값. 합산이 끝나면 하나의 array로 구성하고 다음 col로 넘어감.

array([[ 3,  6,  9],
       [12, 15, 18]])

In [ ]:
data3d.sum(axis=1) # axis=1, Row-Wise 방법, 수평 방향으로 합산한 1차원 array 결과값. 합산이 끝나면 하나의 array로 구성하고 다음 row로 넘어감

array([[5, 7, 9],
       [5, 7, 9],
       [5, 7, 9]])

In [ ]:
data3d.sum(axis=2) # row와 col이 고정된 채로 합산해 하나의 원소를 구성함.

array([[ 6, 15],
       [ 6, 15],
       [ 6, 15]])

In [ ]:
data3d.sum(axis=(0,1)) # [(1+4)+(1+4)+(1+4), (2+5)+(2+5)+(2+5), (3+6)+(3+6)+(3+6)]

array([15, 21, 27])

In [ ]:
data3d.sum(axis=(0,2)) #[(1+2+3)+(1+2+3)+(1+2+3), (4+5+6)+(4+5+6)+(4+5+6)]

array([18, 45])

In [ ]:
data3d.sum(axis=(1,2)) # [(1+2+3+4+5+6), (1+2+3+4+5+6), (1+2+3+4+5+6)]

array([21, 21, 21])

### 위의 3차원 배열에 대한 계산 결과를 간단히 주석으로 설명해보세요